In [ ]:
create 4*4 array with all True values
create 4*4 array with all True values
create 4*4 array whose diagonal element are True and remaining False
create 4*4 array whose diagonal element are False and remaining True

In [ ]:
#Q
divide
multiply
floor_divide
power 
mod

In [12]:
#create 4*4 array with all True values
import numpy as np
np.full((4,4),True,dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
#create 4*4 array with all False values
np.full((4,4),False,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [11]:
#create 4*4 array whose diagonal element are True and remaining False
np.identity(4,dtype='bool')

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [14]:
#create 4*4 array whose diagonal element are False and remaining True
~np.identity(4,dtype='bool')

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [15]:
n=np.array([[20,40,60],[60,80,100]])

In [16]:
n

array([[ 20,  40,  60],
       [ 60,  80, 100]])

In [17]:
#divide
np.divide(n,5)

array([[ 4.,  8., 12.],
       [12., 16., 20.]])

In [18]:
#multiply
np.multiply(n,10)

array([[ 200,  400,  600],
       [ 600,  800, 1000]])

In [20]:
#floor_divide
a1 = np.array([10, 20, 30])
a2 = np.array([3, 7, 5])

np.floor_divide(a1, a2)

array([3, 2, 6], dtype=int32)

In [21]:
#power
np.power(n,2)

array([[  400,  1600,  3600],
       [ 3600,  6400, 10000]], dtype=int32)

In [24]:
#mod
np.mod(n,7)

array([[6, 5, 4],
       [4, 3, 2]], dtype=int32)